//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butler.Model.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ButlerEntities : DbContext
    {
        public ButlerEntities()
            : base("name=ButlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ControlCenter> ControlCenter { get; set; }
        public virtual DbSet<ControllerCategory> ControllerCategory { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobDetail> JobDetail { get; set; }
        public virtual DbSet<JobWorker> JobWorker { get; set; }
        public virtual DbSet<MaterialCost> MaterialCost { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Reference> Reference { get; set; }
        public virtual DbSet<ServiceRating> ServiceRating { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<UserFileUpload> UserFileUpload { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkerAttendance> WorkerAttendance { get; set; }
        public virtual DbSet<Others> Others { get; set; }
        public virtual DbSet<ContactUs> ContactUs { get; set; }
        public virtual DbSet<Quotations> Quotations { get; set; }
    }
}
